import { browserPlatformAdapter } from "./browserPlatformAdapter";
import type { PlatformAdapter } from "./PlatformAdapter";
import { isTauri } from "@tauri-apps/api/core";
import { save } from "@tauri-apps/plugin-dialog";
import { writeFile } from "@tauri-apps/plugin-fs";

/**
 * The browser adapter deliberately remains the default for Vite/dev-shell
 * usage.  In a packaged Tauri window the save dialog grants the selected path
 * to the fs plugin, after which the generated bytes can be written directly.
 */
const tauriPlatformAdapter: PlatformAdapter = {
  ...browserPlatformAdapter,
  async saveFile(data: Blob, suggestedName: string): Promise<boolean> {
    const target = await save({
      defaultPath: suggestedName,
    });
    if (!target) return false;

    await writeFile(target, new Uint8Array(await data.arrayBuffer()));
    return true;
  },
};

// Tauri renders the React UI inside a WebView; feature code uses this boundary
// instead of coupling directly to browser globals.
export function getPlatformAdapter(): PlatformAdapter {
  return isTauri() ? tauriPlatformAdapter : browserPlatformAdapter;
}
